### ISSUE TITLE
Eskom SePush API - Feedback

### ISSUE THREAD

**Issue by wernerhp** [wernerhp/ha.integration.load_shedding#28]
For those who are brave, a very rough development version that works with EskomSePush API is available as a pre-release.
Please post feedback on this issue.

**Comment by DravenSA** [comment]
I was brave.... but then this happened LOL
![Screenshot 2022-10-19 221318](https://user-images.githubusercontent.com/25724682/196794436-b4701efe-e03b-4221-8dd3-ca329b52bd29.jpg)
:-(

**Comment by wernerhp** [comment]
You can request an EskomSePush API Key from [here](https://docs.google.com/forms/d/e/1FAIpQLSeZhAkhDaQX_mLT2xn41TkVjLkOH3Py3YWHi_UqQP4niOY01g/viewform).  See the release notes.

**Comment by DravenSA** [comment]
I have requested for an API key, I selected 50-150 (oops) and the last question on the page? i mean seriously what's that about? I selected data serialization (probably wrong) then i looked up the API Documents and that was no help QUOTE"What is an API / how do I use this / what is a Header / where do I input the Token / why do you want to know about Jason

* Google and/or ask a friend. We unfortunately can't help you right now ..." Un Quote
*
Seriously? 

Typical Eskom making things more difficult than it needs to be. 
AND i still dont know the answer

**Comment by rob196** [comment]
Thanks @wernerhp, just set it up - so far looks good

Just want to confirm the tweak to get the correct time range for the next set of load shedding?

- Used the below as next_end_tme comes back as 0

```
{{ (state_attr("sensor.load_shedding_AREA", "forecast")[0]["start_time"] |
      as_datetime | as_local).strftime("%H:%M") }}  -  {{
      (state_attr("sensor.load_shedding_AREA", "forecast")[0]["end_time"] |
      as_datetime | as_local).strftime("%H:%M") }}
```

Also how often does it update - API call?
And I see that the starts_in has not updated (been about 20 min), is it possible to have this field possible update every minute (or X minutes) - without API call?

FYI - Attributes:
```
attribution: Data provided by sepush.co.za
stage: 0
start_time: 0
end_time: 0
ends_in: 0
starts_in: 643
next_stage: 3
next_start_time: '2022-10-20T16:00:00+00:00'
next_end_time: 0
forecast:
  - stage: 3
    start_time: '2022-10-20T16:00:00+00:00'
    end_time: '2022-10-20T18:30:00+00:00'
  - stage: 3
    start_time: '2022-10-20T22:00:00+00:00'
    end_time: '2022-10-21T00:30:00+00:00'
  - stage: 3
    start_time: '2022-10-21T06:00:00+00:00'
    end_time: '2022-10-21T08:30:00+00:00'
schedule: []
icon: mdi:calendar
friendly_name: Load Shedding AREA
```
