### ISSUE TITLE
Issue with card 1 template

### ISSUE THREAD

**Issue by ethanbenj** [wernerhp/ha.integration.load_shedding#43]
Hi,

Firstly, thank you for the awesome integration.

I am having an issue with the Card 1 template.
Below is what it looks like for me
![image](https://user-images.githubusercontent.com/67481089/202845911-356fbe9e-882a-4a3a-818f-27501c28d033.png)

The time always shows 02:00-02:00. Not sure where I have gone wrong as the card 3 template works brilliant

![image](https://user-images.githubusercontent.com/67481089/202845928-c52012a2-3710-432c-8b88-5e39e67cbdab.png)

Code below. 

Thanks in advance.

`type: entities
entities:
  - type: custom:template-entity-row
    icon: mdi:lightning-bolt-outline
    name: Status
    entity: sensor.load_shedding_eskom_stage
    active: '{{ not is_state("sensor.load_shedding_stage_eskom", "No Load Shedding") }}'
    state: '{{states("sensor.load_shedding_stage_eskom")}}'
  - type: custom:template-entity-row
    icon: mdi:timer-outline
    name: Edenvale
    active: '{{ states("sensor.load_shedding_area_ekurhuleni3_9_edenvale") == "on" }}'
    state: >-
      {{ (state_attr("sensor.load_shedding_area_ekurhuleni3_9_edenvale",
      "start_time") | as_datetime | as_local).strftime("%H:%M") }}  -  {{
      (state_attr("sensor.load_shedding_area_ekurhuleni3_9_edenvale",
      "end_time") | as_datetime | as_local).strftime("%H:%M") }}
    secondary: >-
      {% if states("sensor.load_shedding_area_ekurhuleni3_9_edenvale") == "off"
      %} Starts in {{
      timedelta(minutes=state_attr("sensor.load_shedding_area_ekurhuleni3_9_edenvale",
      "starts_in")) }} {% else %} Ends in {{
      timedelta(minutes=state_attr("sensor.load_shedding_area_ekurhuleni3_9_edenvale",
      "ends_in")) }} {% endif %}
    entity: sensor.load_shedding_area_ekurhuleni3_9_edenvale
`

**Comment by wernerhp** [comment]
The example hasn't been updated for the latest version.  It should be as follows....
<details>
<summary>Code</summary>

```yaml
type: entities
entities:
  - type: custom:template-entity-row
    icon: mdi:lightning-bolt-outline
    name: Status
    entity: sensor.load_shedding_stage_eskom
    active: '{{ not is_state("sensor.load_shedding_stage_eskom", "No Load Shedding") }}'
    state: '{{states("sensor.load_shedding_stage_eskom")}}'
  - type: custom:template-entity-row
    icon: mdi:timer-outline
    name: Milnerton
    active: >-
      {{ states("sensor.load_shedding_area_eskde_14_milnertoncityofcapetownwesterncape") == "on" }}
    state: >-
      {{ (state_attr("sensor.load_shedding_area_eskde_14_milnertoncityofcapetownwesterncape",
      "next_start_time") | as_datetime | as_local).strftime("%H:%M") }} -  {{
      (state_attr("sensor.load_shedding_area_eskde_14_milnertoncityofcapetownwesterncape",
      "next_end_time") | as_datetime | as_local).strftime("%H:%M") }}
    secondary: >-
      {% if states("sensor.load_shedding_milnerton_14") == "off" %} Starts in {{
      timedelta(minutes=state_attr("sensor.load_shedding_area_eskde_14_milnertoncityofcapetownwesterncape",
      "next_start_time")) }} {% else %} Ends in {{
      timedelta(minutes=state_attr("sensor.load_shedding_area_eskde_14_milnertoncityofcapetownwesterncape",
      "next_end_time")) }} {% endif %}
    entity: sensor.load_shedding_area_eskde_14_milnertoncityofcapetownwesterncape
```
</details>
