### ISSUE TITLE
api from eskom se push

### ISSUE THREAD

**Issue by sunsetseatime** [wernerhp/ha.integration.load_shedding#58]
Thanks for this. Saved me so much time.
Im trying to figure out how to plug my API into the mushrooms (lol) so it reads my limit etc.
Right now I have no clue
Sorry for the inconvenience

**Comment by emeyedeejay** [comment]
> 

Add something along these lines to your sensor: section in config.yaml

```
  - platform: rest
    name: EskomSePushAllowance
    resource: https://developer.sepush.co.za/business/2.0/api_allowance
    headers:
      Token: !secret EskomSePush
    json_attributes_path: "$.allowance"
    json_attributes:
      - count
      - limit
      - type
    value_template: "OK"
    scan_interval: 1800
```

**Comment by tinuva** [comment]
Why? 

if you already run this integration, you can just do this:

```
type: custom:mushroom-chips-card
chips:
  - type: template
    content: '{{state_attr(entity, "count")}}/{{state_attr(entity, "limit")}}'
    entity: sensor.load_shedding_sepush_api_quota
    icon: mdi:api
    tap_action:
      action: more-info
alignment: center

```

Looks like:

![Screenshot 2023-03-24 at 13 12 15](https://user-images.githubusercontent.com/5417682/227506478-ad68e06d-3584-4927-810e-49217d25c413.png)
