### ISSUE TITLE
How to manually force a refresh/API call to EskomSePush? 

### ISSUE THREAD

**Issue by kimfr** [wernerhp/ha.integration.load_shedding#70]
Hello,

Thanks for a really cool integration - really helpful in manage Solar and Battery :-)

With the constant changes in Stages (sometimes with very short notice) - I was wondering if we could get a feature like a "Update button"?
Perhaps something like having a button in Home Assistant which does a API call to EskomSePush for a refresh.

Currently, I often re-load the integration in Home Assistant once I get the push notification from EskomSePush App on my phone to get Home Assistant updated - yeah, I know - I might be impatient ;-) but sometimes it's "urgent" when the changes in Stages are at short notice.

**Comment by tinuva** [comment]
You could probably do it yourself.

Create this automation:
```
  - alias: Reload "Load Shedding"
    description: ""
    trigger:
      - platform: time
        at: "00:00:00"
    condition: []
    action:
      - service: homeassistant.reload_config_entry
        data: {}
        target:
          device_id: 557a41e60d82eecee1b78dda2ca59762
    mode: single
```

Then create a button that runs the automation.
